# Generated by Django 5.0.14 on 2026-02-16 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productflow",
            name="custom_persona_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productflow",
            name="persona_type",
            field=models.CharField(
                choices=[
                    ("rushing_executive", "The Rushing Executive"),
                    ("cautious_first_timer", "The Cautious First-Timer"),
                    ("busy_parent", "The Busy Parent"),
                    ("detail_oriented_analyst", "The Detail-Oriented Analyst"),
                    ("non_tech_senior", "The Non-Tech Senior"),
                    ("custom", "Custom Persona"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_flow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="uploads.productflow",
                    ),
                ),
            ],
        ),
    ]
