# Generated by Django 5.0.14 on 2026-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_productflow_custom_persona_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productflow",
            name="goals",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What the persona should be able to achieve with this flow",
            ),
        ),
    ]
