# Generated by Django 5.0.14 on 2026-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0003_productflow_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="productflow",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productflow",
            name="persona_type",
            field=models.CharField(
                choices=[
                    ("busy_parent", "The Busy Parent"),
                    ("cautious_first_timer", "The Cautious First-Timer"),
                    ("detail_oriented_analyst", "The Detail-Oriented Analyst"),
                    ("non_tech_senior", "The Non-Tech Senior"),
                    ("rushing_executive", "The Rushing Executive"),
                    ("custom", "Custom Persona"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
