# Generated by Django 5.0.14 on 2026-03-05 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_productflow_analysis_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productflow",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productflow",
            name="persona_type",
            field=models.CharField(
                choices=[
                    ("busy_parent", "The Busy Parent"),
                    ("cautious_first_timer", "The Cautious First-Timer"),
                    ("non_tech_senior", "The Non-Tech Senior"),
                    ("rushing_executive", "The Rushing Executive"),
                    ("university_professor", "The University Professor"),
                    ("university_student", "The University Student"),
                    ("custom", "Custom Persona"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
