# Generated by Django 5.0.14 on 2026-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0005_productflow_user_alter_productflow_persona_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productflow",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short name for this test run, e.g. 'Onboarding flow v2'",
                max_length=200,
            ),
        ),
    ]
