# Generated by Django 5.0.14 on 2026-03-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0006_add_name_to_productflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
